name: Validate Commits
description: Validate commits with commitlint using Github Actions.
author: Jesse Oberstein
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  base_ref:
    description: The source of pull request that triggered this workflow (required for pull requests).

  head_ref:
    description: The destination of the pull request that triggered this workflow (required for pull requests).

  target_ref:
    description: The commit sha of the event that triggered this workflow (required for push).
  
  extra_config:
    description: A newline-separated list of commitlint-config npm packages to install.